# Copyright (c) 2024 FajarLaksono. All Rights Reserved.

version: '3'
services:
  test:
    image: golang:1.23.6-alpine
    volumes:
      - ${PWD:-./}:/opt/go/src/fajarlaksono.github.io/laksono-api-service
    working_dir: /opt/go/src/fajarlaksono.github.io/laksono-api-service
    command: /bin/true
    env_file:
      - .env.test
    depends_on:
      # - redis
      - timescaledb
      # - mongo
    links:
      # - redis
      - timescaledb
      # - mongo
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.1

  # redis:
  #   image: redis:7.2.3-alpine3.19
  #   command: --requirepass redispass
  #   ports:
  #     - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:2.1.0-pg12
    container_name: laksono-iam-service-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=laksono
      - POSTGRES_PASSWORD=laksono
      - POSTGRES_DB=laksono
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.3

networks:
  laksono_api_service:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16