# Copyright (c) 2024 FajarLaksono. All Rights Reserved.

version: '3'
services:
  service:
    image: ${SERVICE_TAG}:${REVISION_ID}
    container_name: ${SERVICE_TAG}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - ${PWD:-./}:/srv
    env_file:
      - .env
    depends_on:
      - timescaledb
      - zookeeper
      - kafka
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.1

  worker:
    image: ${SERVICE_TAG}-worker:${REVISION_ID}
    container_name: ${SERVICE_TAG}-worker
    volumes:
      - ${PWD:-./}:/srv
    env_file:
      - .env
    depends_on:
      - timescaledb
      - zookeeper
      - kafka
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.2

  # redis:
  #   image: redis:7.2.3-alpine3.19
  #   command: --requirepass redispass
  #   ports:
  #     - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:2.1.0-pg12
    container_name: laksono-api-service-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=laksono
      - POSTGRES_PASSWORD=laksono
      - POSTGRES_DB=laksono
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.3

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes      
    logging:
      driver: json-file
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.4

  kafka:
    image: bitnami/kafka:3.6.2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    logging:
      driver: json-file
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.5

networks:
  laksono_api_service:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16