# Copyright (c) 2024 FajarLaksono. All Rights Reserved.

version: '3'
services:
  test:
    image: golang:1.23.6-alpine
    volumes:
      - ${PWD:-./}:/opt/go/src/fajarlaksono.github.io/laksono-api-service
    working_dir: /opt/go/src/fajarlaksono.github.io/laksono-api-service
    command: /bin/true
    env_file:
      - .env.test
    depends_on:
      # - redis
      - timescaledb
      # - mongo
    links:
      # - redis
      - timescaledb
      # - mongo
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.1

  # redis:
  #   image: redis:7.2.3-alpine3.19
  #   command: --requirepass redispass
  #   ports:
  #     - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:2.1.0-pg12
    container_name: laksono-iam-service-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=laksono
      - POSTGRES_PASSWORD=laksono
      - POSTGRES_DB=laksono
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.3

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes      
    logging:
      driver: json-file
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties

  kafka:
    image: bitnami/kafka:3.6.2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    logging:
      driver: json-file
    volumes:
      - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties

  websocket:
    image: ${SERVICE_TAG}-websocket:${REVISION_ID}
    container_name: ${SERVICE_TAG}-websocket
    ports:
      - "3000:3000"
    volumes:
      - ${PWD:-./}:/srv
    env_file:
      - .env
    networks:
      laksono_api_service:
        ipv4_address: 172.32.1.6

networks:
  laksono_api_service:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16